spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: nbuser
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 127.0.0.1
    database: 9
    port: 6380
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
    
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.kennen.yebserver.pojo
  configuration:
    map-underscore-to-camel-case: false
    
jwt:
  tokenHeader: Authorization
  secret: yeb-secret
  expiration: 604800
  tokenHead: Bearer